---
title: "Lab 02 - Global plastic waste"
author: "Team Name: Lucy, Zazzie, Gabriel, Joel and Jin"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```


## Load & join data sets

```{r load-data, message = FALSE}
# Member 2 (pair 1) write code to load File 1 data here:

data1 <- read_csv("data/mismanaged-plastic-waste-per-capita.csv")

# Member 4 (pair 2) write code to load File 2 data here:

data2 <- read_csv2("data/per-capita-ocean-plastic-waste.txt")




# Member 6 (pair 3) write code to load File 3 data here:
data3 <- read_tsv("data/UN_country_population.tsv")


# Member 1 (pair 1) write code to load File 4 data here:

data4 <- read_excel("data/UN_country_region.xlsx")

```



```{r join-data, message = FALSE}
# Member 2 (pair 1) write code to create object 'plastic_data_all':

plastic_data_all <- data1



# Member 4 (pair 2) write code to join your data to 'plastic_data_all':

plastic_data_all <- data2 %>%
  select(-name) %>%
  left_join(plastic_data_all, by = "code")


# Member 6 (pair 3) write code to join your data to 'plastic_data_all':

plastic_data_all <- data3 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")


# Member 1 (pair 1) write code to join your data to 'plastic_data_all':

plastic_data_all <- data4 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")


```


```{r print-data, message = FALSE}
# Member 2 (pair 1) adds code here to view the first 10 rows of 'plastic_data_all'

plastic_data_all %>%
  head(n = 10)

```



## Exercises

### Ex 1.

```{r Ex1, message = FALSE}
# Write your code here to answer exercise 1
data1 %>%
     left_join(data4, by = "name") %>%
     count(region, sort = TRUE) %>%
     arrange(region)


```



### Ex 2.

```{r Ex2, message = FALSE}
# Write your code here to answer exercise 2

#pt1
plastic_data_all <- mutate(plastic_data_all, 
	total_mismanage_plastic = mismanaged_plastic * population) %>%
  select(code, name, total_mismanage_plastic, everything())

#pt2
plastic_data_all %>%
	group_by(region) %>%
	summarise(
	mean_total_waste = mean(total_mismanage_plastic)
	)

#pt3

plastic_data_all %>%
  group_by(region) %>%
  summarise(
  min_total_waste = min(total_mismanage_plastic)) %>%
  arrange(min_total_waste) %>%
  head(n=1)

plastic_data_all %>%
  group_by(region) %>%
  summarise(
  max_total_waste = max(total_mismanage_plastic)) %>%
  arrange(max_total_waste) %>%
  head(n=1)

#interpreted question as minimum/max of one country in that region of the total_mismanage_waste)


```


### Ex 3.

```{r Ex3, message = FALSE}
# Write your code here to answer exercise 3



```


### Ex 4.

```{r Ex4, message = FALSE}
# Write your code here to answer exercise 4



```
